# Generated by Django 5.1.5 on 2025-01-28 10:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0002_destination_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="desc",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
