# Generated by Django 5.1.5 on 2025-01-29 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0004_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
