# Generated by Django 5.1.5 on 2025-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0007_comments_like_count_comments_liked_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPViewTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("viewed_destinations", models.JSONField(default=list)),
            ],
        ),
    ]
